// This file was generated by Prisma and assumes you have installed the following:
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: process.env.DATABASE_URL || (process.env.CI ? 'postgresql://placeholder:placeholder@localhost:5432/placeholder' : (() => { throw new Error('DATABASE_URL is required') })())
  }
})
