name: ci

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Install dependencies
        run: bun install --ignore-scripts

      - name: Prepare Nuxt
        run: bunx nuxt prepare

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck
